export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGOUT = "LOGOUT"

// Patient
export const AADHAAR_FOUND = "AADHAAR_FOUND"
export const AADHAAR_VERIFICATION_FAIL = "AADHAAR_VERIFICATION_FAIL"
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"
export const OTP_VERIFICATION_FAIL = "OTP_VERIFICATION_FAIL"
export const LOAD_PATIENT_UIDAI_DETAILS = "LOAD_PATIENT_UIDAI_DETAILS"